// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://junmzokrrejwcshgxvoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1bm16b2tycmVqd2NzaGd4dm9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NzcyNzYsImV4cCI6MjA3MzU1MzI3Nn0.aYKyPI_Sxma4r97q61uHNjFMhF8K0zGfNiuDfx8BKJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});